### ISSUE TITLE
What's the correct way to download and place pretrained SD-2-base?

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [NJU-PCALab/AddSR#11]
Hi,

What's the correct way to download and place pretrained SD-2-base? I downloaded 512-base-ema.ckpt and put it to preset/models/stable-diffusion-2-base, but I got the following error. 

Traceback (most recent call last):
  File "test_addsr.py", line 265, in <module>
    main(args)
  File "test_addsr.py", line 162, in main
    pipeline = load_addsr_pipeline(args, accelerator, enable_xformers_memory_efficient_attention)
  File "test_addsr.py", line 73, in load_addsr_pipeline
    scheduler = DDPMScheduler.from_pretrained(args.pretrained_model_path, subfolder="scheduler")
  File "/flash/zhihaoz/conda/envs/addsr2/lib/python3.8/site-packages/diffusers/schedulers/scheduling_utils.py", line 140, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/flash/zhihaoz/conda/envs/addsr2/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 364, in load_config
    raise EnvironmentError(
OSError: Error no file named scheduler_config.json found in directory preset/models/stable-diffusion-2-base.

Thanks.

**Comment by meng-yuan321** [comment]
I have the same problem. Have you solved it?

**Comment by ManuBN786** [comment]
You meant this link ? https://github.com/Stability-AI/stablediffusion

**Comment by Oguzhanercan** [comment]
> You meant this link ? https://github.com/Stability-AI/stablediffusion

https://huggingface.co/stabilityai/stable-diffusion-2-base

you need to install git lfs first.
