### ISSUE TITLE
AttributeError: 'DDPMScheduler' object has no attribute 'get_z0'

### ISSUE THREAD

**Issue by YaqiWangCV** [NJU-PCALab/AddSR#12]
![Snipaste_2024-06-05_15-07-51](https://github.com/NJU-PCALab/AddSR/assets/149864650/35b87855-7012-4f1a-b32c-990895937291)
AttributeError: 'DDPMScheduler' object has no attribute 'get_z0'

**Comment by Oguzhanercan** [comment]
@YaqiWangCV how did you solve it

**Comment by YaqiWangCV** [comment]
By replacing `from diffusers import DDPMScheduler` to `from utils.scheduling_ddpm import DDPMScheduler`

**Comment by Oguzhanercan** [comment]
I belive that ..utils.configuration_utils becomes diffusers.configuration_utils etc. But what about .scheduling_utils in scheduling_ddpm.py file?

**Comment by YaqiWangCV** [comment]
`from diffusers.schedulers import KarrasDiffusionSchedulers, SchedulerMixin`

**Comment by Oguzhanercan** [comment]
> `from diffusers.schedulers import KarrasDiffusionSchedulers, SchedulerMixin`

Thanks a lot.

**Comment by teolcay** [comment]
> > `from diffusers.schedulers import KarrasDiffusionSchedulers, SchedulerMixin`
> 
> Thanks a lot.

DDPMScheduler' object has no attribute 'get_z0 hatasını hala alıyorum şu hatayı veriyor : 
Traceback (most recent call last):
  File "C:\Users\olcay\Desktop\aa-projects\AddSR-Project\AddSR\test_addsr.py", line 265, in <module>
    main(args)
  File "C:\Users\olcay\Desktop\aa-projects\AddSR-Project\AddSR\test_addsr.py", line 214, in main
    image = pipeline(
  File "C:\Users\olcay\Desktop\aa-projects\AddSR-Project\AddSR\utils\vaehook.py", line 444, in wrapper
    ret = fn(*args, **kwargs)
  File "C:\Users\olcay\anaconda3\envs\addsr\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\olcay\Desktop\aa-projects\AddSR-Project\AddSR\pipelines\pipeline_addsr.py", line 1230, in __call__
    latents = self.scheduler.get_z0(latent_model_input, noise_pred, t)
  File "C:\Users\olcay\anaconda3\envs\addsr\lib\site-packages\diffusers\configuration_utils.py", line 142, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DDPMScheduler' object has no attribute 'get_z0'  
how can i fix this ? (türkçe yazarsanız da olur :) )
